aws-samples/busy-engineers-document-bucket

dev/README.md
=> fix(cdk): Update README with launch instructions for workshop devs.

cdk/bin/cdk.ts, cdk/package-lock.json, cdk/package.json, config.toml, dev/cloud9-generator/Makefile, dev/cloud9-generator/bin/cloud9-generator.ts, dev/cloud9-generator/package-lock.json, dev/cloud9-generator/package.json
=> feat: Initial TOML-based system config and plumbing.

cdk/bin/cdk.ts, cdk/package-lock.json, cdk/package.json, config.toml, dev/cloud9-generator/bin/cloud9-generator.ts, dev/cloud9-generator/package-lock.json, dev/cloud9-generator/package.json
Original TOML choice appears to be parser-only.
@iarna/toml deserializes and serializes.
Also make a small tweak to config.toml structure.
=> fix: Switch TOML library.

cdk/bin/cdk.ts, cdk/lib/website-stack.ts, cdk/package-lock.json, cdk/package.json
*Issue #, if available:* #9 
*Description of changes:* Better typing on TOML parser objects. Fix some dependency statuses.
=> fix: Fix TOML types

cdk/package-lock.json, cdk/package.json
*Description of changes:* Upgrade to CDK dependencies.
=> fix(cdk): Upgrades to CDK and dependencies.

cdk/bin/cdk_state.ts, cdk/bin/create_grants.ts, cdk/bin/revoke_grants.ts, cdk/lib/exports.ts, cdk/lib/grant_helpers.ts, cdk/lib/kms-cmk-stack.ts, cdk/package-lock.json, cdk/package.json, exercises/config.toml
=> feat: Add KMS information

exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Api.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Config.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/BaseItem.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/ContextItem.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/DataModelException.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/DocumentBundle.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/PointerItem.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/BaseItemTest.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/ContextItemTest.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/DocumentBundleTest.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/PointerItemTest.java
* Fill out the logic of the API more completely.
* Some updates/additions to the `datamodel` classes.
* Unit tests for `datamodel` accordingly.
* Updates to the `Config` magic TOML mapper class.
Not ideal practice, but I am leaving API tests to a future commit - it'll involve some complexity/mocking and I want to get what I have out for review sooner to make sure it is consistent and on track. (And to keep the PRs smaller.)
=> feat(java): Filing out API logic.

.gitignore, exercises/javascript/.gitignore, exercises/javascript/node-encryption-context-complete/config.js, exercises/javascript/node-encryption-context-complete/index.js, exercises/javascript/node-encryption-context-complete/list.js, exercises/javascript/node-encryption-context-complete/package-lock.json, exercises/javascript/node-encryption-context-complete/package.json, exercises/javascript/node-encryption-context-complete/retrieve.js, exercises/javascript/node-encryption-context-complete/search.js, exercises/javascript/node-encryption-context-complete/store.js
=> feat: Adding JavaScript for Node.js

exercises/java/Makefile
*Description of changes:* Does what it says on the tin.
=> fix(java): Corretto not universally in repos yet; back to wget/rpm install.

cdk/package-lock.json, cdk/package.json
*Description of changes:* Includes `npm audit fix` for security things.
=> fix(cdk): Upgrade CDK dependencies.

Makefile, cdk/Makefile, exercises/javascript/Makefile, exercises/python/Makefile
Organize all the makefiles into a single target
=> feat: Organizing Makefiles

exercises/javascript/node-encryption-context-complete/config.js, exercises/javascript/node-encryption-context-complete/retrieve.js, exercises/javascript/node-encryption-context-complete/store.js
No tests.
Small syntax issues.
=> fix: Small syntax issues

exercises/javascript/Makefile, exercises/javascript/node-encryption-context-complete/package-lock.json
Every exersise will need to have the proper modules installed.
Also, update the `untildify` in package-lock.json
=> feat(javascript): Update Makefile

exercises/javascript/node-encryption-context-complete/cli.js, exercises/javascript/node-encryption-context-complete/package-lock.json, exercises/javascript/node-encryption-context-complete/package.json, exercises/javascript/node-encryption-context-complete/retrieve.js
Add simple CLI to make testing easy
=> feat(javascript): Add simple CLI

exercises/javascript/node-encryption-context-complete/cli.js, exercises/javascript/node-encryption-context-complete/config.js, exercises/javascript/node-encryption-context-complete/index.js, exercises/javascript/node-encryption-context-complete/list.js, exercises/javascript/node-encryption-context-complete/package.json, exercises/javascript/node-encryption-context-complete/retrieve.js, exercises/javascript/node-encryption-context-complete/search.js, exercises/javascript/node-encryption-context-complete/store.js
=> fix: prettier formating

exercises/java/encryption-context-complete/pom.xml, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Api.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Config.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/State.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/BaseItem.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/ContextItem.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/datamodel/DocumentBundle.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/BaseItemTest.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/ContextItemTest.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/DocumentBundleTest.java, exercises/java/encryption-context-complete/src/test/java/sfw/example/esdkworkshop/datamodel/PointerItemTest.java
* Add toString() methods, plus tests.
* Set up state file config plumbing.
* Set up Api to use actual table/bucket state (injected).
* Add Mockito dependency in prep for API tests.
API tests still pending, `datamodel` coverage still 100%.
=> fix(java): Updates from testing.

Makefile
=> fix: bootstrap target needed update.

cdk/bin/cdk.ts, cdk/bin/cdk_state.ts, cdk/bin/create_grants.ts, cdk/bin/revoke_grants.ts, cdk/lib/exports.ts, cdk/lib/grant_helpers.ts, cdk/lib/kms-cmk-stack.ts, cdk/package.json
resolves #38
Add the prettier script and format all files
=> fix(cdk): add and run prettier

dev/README.md
the Makefile in the root of the project coordinates all needed tasks.
=> fix(dev): Update instructions

exercises/python/encryption-context-complete/setup.py, exercises/python/encryption-context-complete/src/document_bucket/__init__.py, exercises/python/encryption-context-complete/src/document_bucket/api.py, exercises/python/encryption-context-complete/src/document_bucket/config.py
Ready to interact in REPL for exercise work.
=> fix(python): Few fixes to last Python exercise.

cdk/lib/config.ts, cdk/lib/exports.ts, cdk/lib/grant_helpers.ts
Add licenses to all cdk files.
#42
=> fix(cdk): add licenses

exercises/python/encryption-context-complete/src/document_bucket/api.py
=> fix(python): Add pointer comments to complete exercise to help students.

exercises/node-javascript/add-esdk-complete/cli.js, exercises/node-javascript/add-esdk-complete/config.js, exercises/node-javascript/add-esdk-complete/index.js, exercises/node-javascript/add-esdk-complete/list.js, exercises/node-javascript/add-esdk-complete/package-lock.json, exercises/node-javascript/add-esdk-complete/package.json, exercises/node-javascript/add-esdk-complete/retrieve.js, exercises/node-javascript/add-esdk-complete/search.js, exercises/node-javascript/add-esdk-complete/store.js, exercises/node-javascript/add-esdk-start/cli.js, exercises/node-javascript/add-esdk-start/config.js, exercises/node-javascript/add-esdk-start/index.js, exercises/node-javascript/add-esdk-start/list.js, exercises/node-javascript/add-esdk-start/package-lock.json, exercises/node-javascript/add-esdk-start/package.json, exercises/node-javascript/add-esdk-start/retrieve.js, exercises/node-javascript/add-esdk-start/search.js, exercises/node-javascript/add-esdk-start/store.js
Add the start and complete code for adding the AWS Encryption SDK.
=> feat(javascript): Add add-esdk

exercises/node-javascript/encryption-context-start/cli.js, exercises/node-javascript/encryption-context-start/config.js, exercises/node-javascript/encryption-context-start/index.js, exercises/node-javascript/encryption-context-start/list.js, exercises/node-javascript/encryption-context-start/package-lock.json, exercises/node-javascript/encryption-context-start/package.json, exercises/node-javascript/encryption-context-start/retrieve.js, exercises/node-javascript/encryption-context-start/search.js, exercises/node-javascript/encryption-context-start/store.js
Add the encryption context start.
Modify the encryption context complete
=> feat(javascript): Add encryption-context

exercises/node-javascript/multi-cmk-complete/cli.js, exercises/node-javascript/multi-cmk-complete/config.js, exercises/node-javascript/multi-cmk-complete/index.js, exercises/node-javascript/multi-cmk-complete/list.js, exercises/node-javascript/multi-cmk-complete/package-lock.json, exercises/node-javascript/multi-cmk-complete/package.json, exercises/node-javascript/multi-cmk-complete/retrieve.js, exercises/node-javascript/multi-cmk-complete/search.js, exercises/node-javascript/multi-cmk-complete/store.js, exercises/node-javascript/multi-cmk-start/cli.js, exercises/node-javascript/multi-cmk-start/config.js, exercises/node-javascript/multi-cmk-start/index.js, exercises/node-javascript/multi-cmk-start/list.js, exercises/node-javascript/multi-cmk-start/package-lock.json, exercises/node-javascript/multi-cmk-start/package.json, exercises/node-javascript/multi-cmk-start/retrieve.js, exercises/node-javascript/multi-cmk-start/search.js, exercises/node-javascript/multi-cmk-start/store.js
Add the start and complete code for the multi cmk.
=> feat(javascript): Add multi-cmk

exercises/node-javascript/add-esdk-complete/retrieve.js, exercises/node-javascript/multi-cmk-start/retrieve.js
The function was left in.
It should be removed.
=> fix(javascript): Remove undefined function

instructions/docs/getting-started.md, instructions/mkdocs.yml
* Set up MkDocs skeleton
* https://github.com/aws-samples/aws-security-workshops is our new look n' feel, which uses MkDocs
* First cut Getting Started instructions
=> feat(docs): Add MkDocs skeleton and Getting Started instructions.

instructions/docs/add-the-encryption-sdk.md
=> feat(docs): Instructions for adding AWS Encryption SDK (Python only).

instructions/docs/add-the-encryption-sdk.md
Instructions for node-javascript add-esdk-start.
=> feat(docs): node-javascript add encryption sdk

Makefile, exercises/python/add-esdk-start/src/document_bucket/api.py, instructions/docs/add-the-encryption-sdk.md, instructions/docs/getting-started.md
=> fix(docs): Fixes from feedback on documentation.

exercises/node-javascript/add-esdk-complete/retrieve.js, exercises/node-javascript/add-esdk-complete/store.js, exercises/node-javascript/add-esdk-start/retrieve.js, exercises/node-javascript/add-esdk-start/store.js, exercises/node-javascript/encryption-context-complete/retrieve.js, exercises/node-javascript/encryption-context-complete/store.js, exercises/node-javascript/encryption-context-start/retrieve.js, exercises/node-javascript/encryption-context-start/store.js, exercises/node-javascript/multi-cmk-complete/retrieve.js, exercises/node-javascript/multi-cmk-complete/store.js, exercises/node-javascript/multi-cmk-start/retrieve.js, exercises/node-javascript/multi-cmk-start/store.js, instructions/docs/add-the-encryption-sdk.md
Make the comments and instructions more targeted.
=> feat(javascript): Better comments and instructions

cdk/Makefile, cdk/bin/revoke_faythe_grants.ts, cdk/bin/revoke_walter_grants.ts, exercises/Makefile, exercises/python/multi-cmk-start/src/document_bucket/__init__.py, instructions/docs/encryption-context.md, instructions/docs/index.md, instructions/docs/multi-cmk.md
* Initial cut Multi-CMK instructions (incomplete)
* Related updates to `Makefile`s for convenience targets for students
* Opportunistic improvement of Python comments (#66)
* Outline placeholder for the Encryption Context exercise
Edit: Forgot, temporary (easier-reading) preview here: https://lizroth.github.io/busy-engineers-document-bucket/multi-cmk/
=> feat(docs): Rough draft of Multi-CMK instructions, and related updates.

instructions/docs/add-the-encryption-sdk.md, instructions/docs/multi-cmk.md
* Add save and exit instructions
* Add REPL and CLI usage for multi-cmk
* Better REPL and CLI usage for add-the-encryption
=> fix(javascript): Better REPL and cli instructions

exercises/node-javascript/add-esdk-complete/retrieve.js, exercises/node-javascript/add-esdk-complete/store.js, exercises/node-javascript/add-esdk-start/retrieve.js, exercises/node-javascript/add-esdk-start/store.js, exercises/node-javascript/encryption-context-complete/retrieve.js, exercises/node-javascript/encryption-context-complete/store.js, exercises/node-javascript/encryption-context-start/retrieve.js, exercises/node-javascript/encryption-context-start/store.js, exercises/node-javascript/multi-cmk-complete/retrieve.js, exercises/node-javascript/multi-cmk-complete/store.js, exercises/node-typescript/add-esdk-complete/src/retrieve.ts, exercises/node-typescript/add-esdk-complete/src/store.ts, exercises/node-typescript/add-esdk-start/src/retrieve.ts, exercises/node-typescript/add-esdk-start/src/store.ts, exercises/node-typescript/encryption-context-complete/src/retrieve.ts, exercises/node-typescript/encryption-context-complete/src/store.ts, exercises/node-typescript/encryption-context-start/src/retrieve.ts, exercises/node-typescript/encryption-context-start/src/store.ts, exercises/python/add-esdk-complete/src/document_bucket/__init__.py, exercises/python/add-esdk-complete/src/document_bucket/api.py, exercises/python/encryption-context-start/src/document_bucket/api.py, exercises/python/multi-cmk-complete/src/document_bucket/__init__.py
*Issue #, if available:* #66
Scope: JS, TS, and remaining Python exercises. (Java not yet merged and should already be up to date.)
Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/66
=> fix: Make pointer comments consistent with doc headings and state.

exercises/python/add-esdk-complete/src/document_bucket/model.py, exercises/python/encryption-context-complete/src/document_bucket/api.py, exercises/python/encryption-context-complete/src/document_bucket/model.py, exercises/python/encryption-context-complete/test/test_api.py, exercises/python/encryption-context-start/src/document_bucket/model.py, exercises/python/multi-cmk-complete/src/document_bucket/model.py, exercises/python/multi-cmk-start/src/document_bucket/model.py
*Issue #, if available:* #92
Backport related fixes.
Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/92
=> fix(python): Use correct key and context in EC exercise.

exercises/node-javascript/encryption-context-complete/retrieve.js, exercises/node-javascript/encryption-context-start/retrieve.js, exercises/node-typescript/encryption-context-complete/src/retrieve.ts, exercises/node-typescript/encryption-context-start/src/retrieve.ts, instructions/docs/encryption-context.md
Update Javascript
Update Typescript
small Python fix
=> Add Encryption Context instructions

dev/cloud9-generator/bin/cloud9-generator.ts
=> fix(cdk): Cloud9 generator needed config.toml path update.

exercises/node-typescript/Makefile
=> fix(typescript): make target name

instructions/docs/add-the-encryption-sdk.md, instructions/docs/encryption-context.md, instructions/docs/multi-cmk.md
Javascript and Typescript for #84 
=> Line highlight

exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/App.java, instructions/docs/CNAME, instructions/docs/add-the-encryption-sdk.md, instructions/docs/encryption-context.md, instructions/docs/getting-started.md, instructions/docs/multi-cmk.md, instructions/docs/thank-you-and-closing.md
* https://github.com/aws-samples/busy-engineers-document-bucket/issues/106
* https://github.com/aws-samples/busy-engineers-document-bucket/issues/84
* https://github.com/aws-samples/busy-engineers-document-bucket/issues/82
* https://github.com/aws-samples/busy-engineers-document-bucket/issues/81
* https://github.com/aws-samples/busy-engineers-document-bucket/issues/80
*Description of changes:* All together, this change addresses the following:
* Feedback/documentation suggestions from reviewers
* Java examples everywhere
* Minor standardization tweaks to instructions
* Expanding TODOs
* CNAME configuration (fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/106 )
* Change highlighting (fixes …
=> feat(docs): Try it Out examples, highlight fixes, and other fixes from feedback.

exercises/node-javascript/add-esdk-complete/list.js, exercises/node-javascript/add-esdk-complete/search.js, exercises/node-javascript/add-esdk-start/list.js, exercises/node-javascript/add-esdk-start/search.js, exercises/node-javascript/encryption-context-complete/list.js, exercises/node-javascript/encryption-context-complete/search.js, exercises/node-javascript/encryption-context-start/list.js, exercises/node-javascript/encryption-context-start/search.js, exercises/node-javascript/multi-cmk-complete/list.js, exercises/node-javascript/multi-cmk-complete/search.js, exercises/node-javascript/multi-cmk-start/list.js, exercises/node-javascript/multi-cmk-start/search.js
=> fix(javascript): Remove unused comments

exercises/node-javascript/Makefile
Make needs to be told to call the shell
to use curl
=> fix(workshop): Make needs to call the shell

instructions/docs/getting-started.md
=> Small grammer typo

instructions/docs/add-the-encryption-sdk.md
=> removing dangling `for`

exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/Api.java, exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/App.java, exercises/python/add-esdk-complete/src/document_bucket/__init__.py, exercises/python/encryption-context-complete/src/document_bucket/__init__.py, exercises/python/encryption-context-start/src/document_bucket/__init__.py, exercises/python/multi-cmk-complete/src/document_bucket/__init__.py, exercises/python/multi-cmk-start/src/document_bucket/__init__.py, instructions/docs/add-the-encryption-sdk.md, instructions/docs/encryption-context.md, instructions/docs/multi-cmk.md
=> Fixes from feedback during workshop test run.

exercises/java/add-esdk-complete/startup.jsh, exercises/java/add-esdk-start/startup.jsh, exercises/java/encryption-context-complete/startup.jsh, exercises/java/encryption-context-start/startup.jsh, exercises/java/multi-cmk-complete/startup.jsh, exercises/java/multi-cmk-start/startup.jsh
=> fix(java): Add missing import to jshell startup.

instructions/docs/add-the-encryption-sdk.md, instructions/docs/encryption-context.md, instructions/docs/multi-cmk.md
* Adding full file path for TS/JS
* update few path errors
* Add missing JS/TS to REPL instructions
=> fix(workshop): Update instructions from feedback

instructions/docs/encryption-context.md
=> fix(workshop): More path errors

instructions/docs/add-the-encryption-sdk.md, instructions/docs/encryption-context.md, instructions/docs/multi-cmk.md
=> fix(java): Add missing calls to AttributeValue#getS()

exercises/python/Makefile, exercises/python/encryption-context-complete/setup.py, exercises/python/encryption-context-start/setup.py, exercises/python/multi-cmk-complete/setup.py
=> fix(python): Add missing license headers.

instructions/docs/index.md, instructions/mkdocs.yml
*Issue #, if available:* Fixes #145 
=> fix(docs): Promote exercises to top-level nav.

exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/State.java, exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/State.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/State.java, exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/State.java, exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/State.java, exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/State.java
Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/124
=> fix(java): Expand ~ in path to state file.

instructions/docs/tips-and-troubleshooting.md, instructions/mkdocs.yml
*Issue #, if available:* Fixes several issues:
* Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/120
* Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/136
* Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/83
=> feat(docs): Tips and Troubleshooting section in docs.

README.md, cdk/README.md, dev/README.md, exercises/README.md, instructions/README.md
*Issue #, if available:* Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/90
=> fix(docs): READMEs.

instructions/docs/getting-started.md
=> fix(docs): Add warning about not switching region.

instructions/docs/multi-cmk.md
*Issue #, if available:* Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/128
=> fix(docs): Add note about generator CMKs in keyrings.

cdk/Makefile, cdk/bin/list_grants.ts, cdk/bin/revoke_faythe_grants.ts, cdk/bin/revoke_walter_grants.ts, cdk/lib/kms-cmk-stack.ts, instructions/docs/multi-cmk.md
*Issue #, if available:* https://github.com/aws-samples/busy-engineers-document-bucket/issues/139
* Add key policy without data key operations to KMS CDK stack
* Add `list_grants.ts` with utilities to display the current state of grants on the CMKs
* Add `make list_grants` for workshop students to inspect the state of grants on the CMKs
=> Adjust key policies, add grant inspection target.

exercises/Makefile, instructions/docs/multi-cmk.md
*Issue #, if available:* Unblocks https://github.com/aws-samples/busy-engineers-document-bucket/issues/76
* Quick links to various KMS operations in Faythe's region and in Walter's region
* Add referenced `make` target to the `exercises` directory (forgot to propagate)
=> Add filtered CloudTrail links.

cdk/package-lock.json, cdk/package.json
=> chore(cdk): Update versions

instructions/docs/tips-and-troubleshooting.md
Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/153
Unblocks https://github.com/aws-samples/busy-engineers-document-bucket/issues/23
Preview: http://document-bucket.awssecworkshops.com/tips-and-troubleshooting/#api-documentation
=> fix(docs): Instructions to get to API docs.

exercises/python/add-esdk-complete/src/document_bucket/model.py, exercises/python/add-esdk-start/src/document_bucket/model.py, exercises/python/encryption-context-complete/src/document_bucket/model.py, exercises/python/encryption-context-start/src/document_bucket/model.py, exercises/python/multi-cmk-complete/src/document_bucket/model.py, exercises/python/multi-cmk-start/src/document_bucket/model.py
*Issue #, if available:* #161 
=> fix(python): Fix type error in model.

instructions/docs/encryption-context.md
=> docs: Fix small typo in opening description

instructions/docs/encryption-context.md
Swap javascript and type script samples so the exercise tabs are consequent in the same order for exercise 3 (Exercise 3: Working With Encryption Context)
=> docs: Swap javascript and typescript tom make the instructions consequent

exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/Api.java, exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/StateConfig.java, exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/StateConfig.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/StateConfig.java, exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/StateConfig.java, exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/StateConfig.java, exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/App.java, exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/StateConfig.java, instructions/docs/add-the-encryption-sdk.md, instructions/docs/multi-cmk.md
*Description of changes:* Java state parsing was broken. Fix it.
=> Fix bug with Java state parsing.

exercises/python/Makefile
*Issue #, if available:* fixes #175 
Upgrade `pip` to the latest version before trying to use it.
=> fix: upgrade pip

Makefile, cdk/bin/resize.sh
As part of the bootstrap just resize the volume.
Related: #166 
=> feat(cdk): Resize the volume

README.md
=> chore: Add security issue notification to readme

.github/dependabot.yml, cdk/package-lock.json, cdk/package.json, dev/cloud9-generator/package-lock.json, dev/cloud9-generator/package.json
Updating js and ts dependencies. 
ran `npm install`, `npm audit fix`, `npm update`
Tested that workshop still worked by following instructions on REAME, running through the smoke tests, and kickstarting a workshop with [these](https://document-bucket.awssecworkshops.com/getting-started/) instructions.
=> chore(deps): updating dependencies and enabling dependabot

exercises/python/encryption-context-complete/tox.ini
Must include requirements otherwise, toml is not found
=> chore: include requirements in test

exercises/java/add-esdk-complete/pom.xml, exercises/java/add-esdk-start/pom.xml, exercises/java/encryption-context-complete/pom.xml, exercises/java/encryption-context-start/pom.xml, exercises/java/multi-cmk-complete/pom.xml, exercises/java/multi-cmk-start/pom.xml, instructions/docs/adding-the-encryption-sdk.md, instructions/docs/encryption-context.md, instructions/docs/multi-cmk.md
Also updated the output to be more friendly.
=> fix: update java library versions

cdk/package.json, exercises/node-javascript/add-esdk-complete/package.json, exercises/node-javascript/add-esdk-complete/retrieve.js, exercises/node-javascript/add-esdk-complete/store.js, exercises/node-javascript/add-esdk-start/package.json, exercises/node-javascript/encryption-context-complete/package.json, exercises/node-javascript/encryption-context-start/package.json, exercises/node-javascript/multi-cmk-complete/package.json, exercises/node-javascript/multi-cmk-start/package.json, exercises/node-typescript/add-esdk-complete/package.json, exercises/node-typescript/add-esdk-complete/src/retrieve.ts, exercises/node-typescript/add-esdk-complete/src/store.ts, exercises/node-typescript/add-esdk-start/package.json, exercises/node-typescript/encryption-context-complete/package.json, exercises/node-typescript/encryption-context-start/package.json, exercises/node-typescript/multi-cmk-complete/package.json, exercises/node-typescript/multi-cmk-start/package.json, exercises/python/add-esdk-complete/src/document_bucket/__init__.py, exercises/python/add-esdk-complete/src/document_bucket/api.py, instructions/docs/adding-the-encryption-sdk.md
Make changes as needed to still work.
=> fix: update package version for esdk and aws

exercises/node-javascript/encryption-context-complete/retrieve.js, exercises/node-javascript/encryption-context-complete/store.js, exercises/node-javascript/encryption-context-start/retrieve.js, exercises/node-javascript/encryption-context-start/store.js, exercises/node-javascript/multi-cmk-complete/retrieve.js, exercises/node-javascript/multi-cmk-complete/store.js, exercises/node-javascript/multi-cmk-start/retrieve.js, exercises/node-javascript/multi-cmk-start/store.js, exercises/node-typescript/encryption-context-complete/src/retrieve.ts, exercises/node-typescript/encryption-context-complete/src/store.ts, exercises/node-typescript/encryption-context-start/src/retrieve.ts, exercises/node-typescript/encryption-context-start/src/store.ts, exercises/node-typescript/multi-cmk-complete/src/retrieve.ts, exercises/node-typescript/multi-cmk-complete/src/store.ts, exercises/node-typescript/multi-cmk-start/src/retrieve.ts, exercises/node-typescript/multi-cmk-start/src/store.ts, exercises/python/multi-cmk-complete/src/document_bucket/__init__.py, exercises/python/multi-cmk-complete/src/document_bucket/api.py, exercises/python/multi-cmk-start/src/document_bucket/__init__.py, exercises/python/multi-cmk-start/src/document_bucket/api.py
update ‘add’ and ‘complete’ code to use 3.1.1
=> fix: update to latest version of esdk

instructions/README.md, instructions/mkdocs.yml
*Description of changes:* Fix mkdocs config so that it builds with latest MkDocs release. Add build/verify/deploy instructions to README.
=> Fix mkdocs config and add README to instructions

instructions/README.md
*Description of changes:* Updating deploy instructions. Otherwise if you are working off a fork like we tend to do, you end up just deploying to your fork.
=> fix: Clarify mkdoc deploy in README

cdk/package-lock.json, dev/cloud9-generator/package-lock.json, dev/cloud9-generator/package.json
Verified `make bootstrap` completes successfully
=> chore: Upgrade cdk typscript and jest

instructions/docs/adding-the-encryption-sdk.md, instructions/docs/getting-started.md, instructions/docs/multi-kms-key.md, instructions/mkdocs.yml
Small improvements for correctness and clarity in the instructions.
Verified the build docs look good via `mkdocs serve` and tested the updated python instruction code updates manually.
=> chore: Minor instruction improvements

cdk/lib/exports.ts, exercises/config.toml, instructions/docs/clean-up-and-closing.md, instructions/docs/encryption-context.md, instructions/docs/multi-kms-key.md
Move Walter KMS Key to us-east-1
=> chore: Move Walter resource to us-east-1

cdk/package-lock.json, dev/cloud9-generator/package-lock.json
```
npm i --no-audit
npm audit fix
```
=> chore: Update package-lock
