- cdk/bin/cdk.ts
- cdk/lib/website-stack.ts
- cdk/package-lock.json
- cdk/package.json
- config.toml
Adds several CFN Outputs to use as hooks for configuring Cognito.
There is bootstrapping work to set up Cognito that is not yet done, this just tells CFN to spin up the resources.
NOTE: This is a partial migration to using more TOML configuration. I would like to do this everywhere, but it's an unrelated change to this changeset. So I am doing this only partially to reduce merge conflicts and keep unrelated changes down.
See: https://github.com/aws-samples/busy-engineers-document-bucket/issues/7
> feat(cdk): Add Cognito extension to Website stack.

- cdk/bin/cdk.ts
- cdk/lib/document-bucket-stack.ts
- cdk/lib/kms-cmk-stack.ts
- cdk/lib/webapp-stack.ts
- cdk/lib/website-stack.ts
- cdk/package-lock.json
- cdk/package.json
- config.toml
*Issue #, if available:* https://github.com/aws-samples/busy-engineers-document-bucket/issues/7
*Description of changes:* Get rid of use of string constants to configure various CDK resources. Use the TOML configuration file instead.
Also renames "Website" to "Webapp" to be clearer for the student/customer.
Relative to `master`, this change picks up/builds on a commit from https://github.com/aws-samples/busy-engineers-document-bucket/pull/10 and I may wind up force pushing to do cleanup things.
> fix: Plumb through TOML configuration.

- .gitignore
- cdk/bin/cdk.ts
- cdk/bin/cdk_state.ts
- cdk/lib/config.ts
Add a simple script to export the CloudFormation outputs to a state file.
The outputs from `config.toml` can be looked up as needed.
> feat: export cfn output to state

- cdk/bin/cdk_state.ts
- cdk/package-lock.json
- cdk/package.json
There are many ways to expand `~`.
Node.js does not expand this value.
`untildify` is a good solution to this problem.
> fix: expand ~ for home directories

- exercises/python/Makefile
*Description of changes:* Invoke the `pipenv` installed Python directly to get the right `pip` and install `tox` in the right place.
> fix(python): Different Python bootstrap option to install with correct pip.

- exercises/node-javascript/Makefile
According to https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html
The AWS SDK JS will only look in the ~/.aws/credentials file if AWS_SDK_LOAD_CONFIG is set.
> fix(javascript): Add region config env var

- exercises/node-javascript/Makefile
It seems that AWS_SDK_LOAD_CONFIG does NOT do what is expected.
It will force the ~/.aws/credentials file to *only* load the region
> fix(javascript): Set the AWS_REGION

- instructions/docs/getting-started.md
- instructions/docs/multi-cmk.md
Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/63
*Issue #, if available:* #63
Don't take workshop students away from the exercise content. External links now `target=_blank`. The Markdown/`MkDocs`-way to do that seems to be to directly embed HTML.
> fix(docs): Launch external links in new windows.

- cdk/Makefile
- cdk/package-lock.json
- cdk/package.json
resolves #99
* Move typescript and ts-node to `dependencies`
* Update typescript version
* Update package-lock
* change make file to `npm ci` for reproducable builds in the workshop
> fix(cdk): make state typescript error

- exercises/node-javascript/add-esdk-complete/package-lock.json
- exercises/node-javascript/add-esdk-complete/package.json
- exercises/node-javascript/add-esdk-start/package-lock.json
- exercises/node-javascript/add-esdk-start/package.json
- exercises/node-javascript/encryption-context-complete/package-lock.json
- exercises/node-javascript/encryption-context-complete/package.json
- exercises/node-javascript/encryption-context-start/package-lock.json
- exercises/node-javascript/encryption-context-start/package.json
- exercises/node-javascript/multi-cmk-complete/package-lock.json
- exercises/node-javascript/multi-cmk-complete/package.json
- exercises/node-javascript/multi-cmk-start/package-lock.json
- exercises/node-javascript/multi-cmk-start/package.json
- exercises/node-typescript/add-esdk-complete/package-lock.json
- exercises/node-typescript/add-esdk-complete/package.json
- exercises/node-typescript/add-esdk-start/package-lock.json
- exercises/node-typescript/add-esdk-start/package.json
- exercises/node-typescript/encryption-context-complete/package-lock.json
- exercises/node-typescript/encryption-context-complete/package.json
- exercises/node-typescript/encryption-context-start/package-lock.json
- exercises/node-typescript/encryption-context-start/package.json
- exercises/node-typescript/multi-cmk-complete/package-lock.json
- exercises/node-typescript/multi-cmk-complete/package.json
- exercises/node-typescript/multi-cmk-start/package-lock.json
- exercises/node-typescript/multi-cmk-start/package.json
Bump to latest version 1.0.2 for Typescript and Javascript
> fix: Update version of @aws-crypto/client-node

- cdk/lib/document-bucket-stack.ts
- cdk/lib/webapp-stack.ts
resolves #2
Make sure the buckets are encrypted by default.
This workshop is **NOT** for production data.
The S3 examples should be as conservative
and security-conscious as possible.
> feat(cdk): Encrypt S3 buckets by default

- Makefile
- README.md
- exercises/node-javascript/Makefile
- exercises/node-typescript/Makefile
- exercises/node-typescript/add-esdk-complete/cli.ts
- exercises/node-typescript/add-esdk-start/cli.ts
- exercises/node-typescript/encryption-context-complete/cli.ts
- exercises/node-typescript/encryption-context-start/cli.ts
- exercises/node-typescript/multi-cmk-complete/cli.ts
- exercises/node-typescript/multi-cmk-start/cli.ts
- instructions/docs/getting-started.md
Several fixes:
* Not all distros support env -S
* adding a smoke test for the CLI
* Faster bootstrap (drops about 3 min)
* Edit the readme to add link to the documentation
* Add typescript to the try it out list 
> Fixes and features based on testing the workshop

- exercises/node-javascript/Makefile
The metadata endpoint does not return the region.
It returns the availability zone.
This is the region with an identifier at the end.
Manipulating the string in a Makefile is harder for me than it should be.
> fix(javascript): Makefile variable manipulation

- cdk/Makefile
This is especially important for the bootstrap target.
The deploy *must* complete before the state or grants can be processed.
> fix(cdk): composed targets MUST be serial

- instructions/docs/thank-you-and-closing.md
*Issue #, if available:* #137
Fixes https://github.com/aws-samples/busy-engineers-document-bucket/issues/137
Fix typo about which console the instructions are referring to.
> fix(docs): Use npx for teardown, fix typo.

- .gitignore
- exercises/java/add-esdk-complete/Makefile
- exercises/java/add-esdk-start/Makefile
- exercises/java/encryption-context-complete/Makefile
- exercises/java/encryption-context-start/Makefile
- exercises/java/multi-cmk-complete/Makefile
- exercises/java/multi-cmk-start/Makefile
*Issue #, if available:* Fixes #24.
*Description of changes:* Changes to the Javadoc target to host on a local port that Cloud9 will discover. Students can then browse the Javadoc in the IDE. This will also work fine for browsing outside of C9.
> feat(java): Cloud9 Javadoc hosting.

- exercises/java/Makefile
fixes: #177 
1. Change to install Corretto via the yum repo per https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html
1. Update Maven install to new Apache mirror per https://maven.apache.org/download.cgi and templatize the download/install to make moving to new versions simpler.
> fix: clean up Java bootstrap makefile and move to new Maven mirror

- exercises/python/encryption-context-complete/src/document_bucket/__init__.py
- exercises/python/encryption-context-complete/src/document_bucket/api.py
- exercises/python/encryption-context-complete/test/test_api.py
2.0 introduced new symbols and deprecated others
* Move from removed `KMSMasterKeyProvider` to `StrictAwsKmsMasterKeyProvider`
* Move from top-level `encrypt`/`decrypt` operations to the corresponding ones in `EncryptionSDKClient`
> Update Python example for the 2.0 Python ESDK release

- exercises/java/add-esdk-complete/checkstyle.xml
- exercises/java/add-esdk-start/checkstyle.xml
- exercises/java/encryption-context-complete/checkstyle.xml
- exercises/java/encryption-context-start/checkstyle.xml
- exercises/java/encryption-context-start/pom.xml
- exercises/java/multi-cmk-complete/checkstyle.xml
- exercises/java/multi-cmk-complete/pom.xml
- exercises/java/multi-cmk-start/checkstyle.xml
- exercises/java/multi-cmk-start/pom.xml
*Issue #, if available:* Upgrade all checkstyles to 8.29. Remove deprecated checkstyles properties.
*Description of changes:* manually testing according to https://github.com/aws-samples/busy-engineers-document-bucket#testing
also `mvn install` in every java exercise.
> chore: Upgrade checkstyles

- exercises/java/encryption-context-complete/pom.xml
- exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/App.java
*Issue #, if available:* https://github.com/aws-samples/busy-engineers-document-bucket/issues/204
Primarily updates to account for API changes in ESDK 2.0, but also a minor change to pom.xml to make it easier to test against a specific ESDK version.
*Testing:* 
`mvn verify -Dcheckstyle.skip -Desdk.version=2.0.0` succeeds (previously failed
> chore: Update Java example for the 2.0 Java ESDK release

- buildspec.yml
- codebuild/add-esdk-complete.yml
- codebuild/add-esdk-start.yml
- codebuild/encryption-context-complete.yml
- codebuild/encryption-context-start.yml
- codebuild/multi-cmk-complete.yml
- codebuild/multi-cmk-start.yml
- exercises/java/add-esdk-complete/pom.xml
- exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/App.java
- exercises/java/add-esdk-start/pom.xml
- exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/encryption-context-start/pom.xml
- exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/App.java
- exercises/java/multi-cmk-complete/pom.xml
- exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/App.java
- exercises/java/multi-cmk-start/pom.xml
- exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/App.java
*Issue #, if available:* 
*Description of changes:* Bring all the Java exercises up to the latest ESDK for Java version.
Also add codebuild to test each Java step in CI.
Note: Descriptions at https://document-bucket.awssecworkshops.com/adding-the-encryption-sdk/ are out of date with references to some of the code (and were before this PR)
Note: The CI only builds each step of the workshop for Java. We still have no CI for the other languages, or any of the workshop CFn/cdk stuff.
> Upgrade Java examples and add codebuild

- instructions/docs/adding-the-encryption-sdk.md
- instructions/docs/encryption-context.md
- instructions/docs/getting-started.md
- instructions/docs/multi-cmk.md
- instructions/docs/stylesheets/custom.css
- instructions/docs/tips-and-troubleshooting.md
- instructions/mkdocs.yml
The old style of codeblock tabs are deprecated with the latest version of Materials for MkDocs. This PR updates to use the latest style for tabs with codeblocks, as well as a couple other surface level updates to better match style with https://awssecworkshops.com/
Additionally, a couple of the highlighted lines in the codeblock sections were not updates with the latest commitment changes. This PR fixes these errors.
> fix: Fix code block tabs using latest mkdocs

- instructions/docs/tips-and-troubleshooting.md
Did an audit of external links in our workshop. I have updated ones which get re-directed, or are otherwise out of date. Updated Cloud9 docs to AWS docs, given that those will be more relevant to the workshop.
> fix: Update stale links

- exercises/java/add-esdk-complete/pom.xml
- exercises/java/add-esdk-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/add-esdk-start/pom.xml
- exercises/java/add-esdk-start/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/encryption-context-complete/pom.xml
- exercises/java/encryption-context-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/encryption-context-start/pom.xml
- exercises/java/encryption-context-start/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/multi-cmk-complete/pom.xml
- exercises/java/multi-cmk-complete/src/main/java/sfw/example/esdkworkshop/Api.java
- exercises/java/multi-cmk-start/pom.xml
- exercises/java/multi-cmk-start/src/main/java/sfw/example/esdkworkshop/Api.java
- instructions/docs/adding-the-encryption-sdk.md
- instructions/docs/encryption-context.md
- instructions/docs/multi-cmk.md
*Description of changes:* Fixes the Java instructions to use the newest "complete" version of the code, as well as fix some minor inconsistencies between the "complete" and "start" dirs in exercise 1.
Additionally updates a Cloudtrail link to filter for the right logs (otherwise it defaults to a filter which will never see the KMS logs)
Tested via pulling this branch into cloud9 workshop environment and following instructions build by this fork. Verified that instructions on this fork look good manually.
> fix: Fix Java exercises

- dev/cloud9-generator/bin/cloud9-generator.ts
- dev/cloud9-generator/lib/cloud9-stack.ts
- dev/cloud9-generator/package-lock.json
- dev/cloud9-generator/package.json
- dev/cloud9-generator/tsconfig.json
Adding ImageId param for cloud9 creation as its required for Type: AWS::Cloud9::EnvironmentEC2. cdk upgrade for c9 generator stack to cdkv2
*Issue #, if available:* [290](https://github.com/aws-samples/busy-engineers-document-bucket/issues/290)
*Description of changes:* Adding ImageId param for cloud9 creation as its required for Type: AWS::Cloud9::EnvironmentEC2. cdk upgrade for c9 generator stack to cdkv2
> Adding ImageId param for cloud9 creation as its required for Cloud9
